= Developer Demo: Setup =
:experimental:
:imagesdir: images
:toc:
:toclevels: 4

== Installing Demo ==
[IMPORTANT]
====
* Before running any script commands, make sure the run the following in the appropriate shell.  Note that the first parameter in this command will set the `PROJECT_PREFIX` environment variable which is referenced in many of the instructions.  If not provided, the default is `demo-dev`.
+
----
. scripts/shell-setup.sh 
----
====

=== Setup Prerequisites ===

. Setup your environment or shell variables as outlined <<Variables Used in This Demo,here>>
. Run the following script to install the necessary operators to your cluster
+
----
$DEMO_HOME/scripts/install-prereq.sh
----

=== Main Demo Installation ===

The demo installation will setup all the necessary aspects of the demo which includes:

* Gogs repo
* Tekton Pipeline
* Coolstore Elements (no Payment)
* Optional: Kafka

. Install the main part of the demo by running this command
+
----
$DEMO_HOME/scripts/create-demo.sh -p $PROJECT_PREFIX 
----

== Appendix ==

=== Using jib extensions for quarkus locally ===

You can use the link:https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-quarkus-extension-maven[jib extensions for quarkus] to build and create an image to push to the local registry.  Here are the different commands that you can run.

==== JVM build ====

To build quarkus and move it to the local `payment` imagestream in the current project context run this command

----
mvn '-B' clean package com.google.cloud.tools:jib-maven-plugin:build -Djib.allowInsecureRegistries=true -Djib.to.image="$(oc get is/payment -o jsonpath='{.status.publicDockerImageRepository}')" -Djib.container.mainClass=bogus -Djib.container.ports="8080" -Djib.to.auth.username=$(oc whoami) -Djib.to.auth.password=$(oc whoami -t)
----

You can then update the knative service as so:

----
kn service update payment --image $(oc get is/payment -o jsonpath='{.status.dockerImageRepository}'):latest --revision-name "{{.Service}}-{{.Generation}}" --concurrency-limit=1
----

==== Native build ====

NOTE: Not currently working, as outlined in link:https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-quarkus-extension-maven[jib extensions for quarkus].

NOTE: If running in a docker container, need to ensure that you give enough resources to docker

----
export MAVEN_OPTS=" -Xmx1024M -Xss128M -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1024M -XX:+CMSClassUnloadingEnabled"
mvn '-B' clean package -Pnative com.google.cloud.tools:jib-maven-plugin:build -Duser.home=${HOME} -Djib.allowInsecureRegistries=true -Djib.to.image=$(oc get is/payment -o jsonpath='{.status.publicDockerImageRepository}')" -Djib.container.mainClass=bogus -Djib.container.ports="8080" -Djib.to.auth.username=$(oc whoami) -Djib.to.auth.password=$(oc whoami -t)
----

=== Variables Used in This Demo ===

Here are all the variables that are used for the different commands in this demo

* PROJECT_PREFIX: This is the base name for the projects that will be created (e.g. ${PROJECT_PREFIX}-cicd)

==== Monitoring Kafka Cluster Installation ====

You can tail the logs of the amqstreams operator's logs to determine why an installation is taking so long:

----
stern -l "name=amq-streams-cluster-operator" -n openshift-operators
----

NOTE: stern is installed in the .devcontainer that is in the root of this repo.  If you open the repository folder in a container (using vscode remote) stern is installed on the container.

=== Missing Operator Catalogs ===

If you cannot find the operators referenced then run the following on your cluster

----
oc apply -f "$DEMO_HOME/install/redhat-operators-csc.yaml" \
  -f "$DEMO_HOME/install/community-operators-csc.yaml"

oc -n openshift-marketplace get csc
----

A successful reconciliation should show an output like:

----
NAME                           STATUS      MESSAGE                                       AGE
community-operators-packages   Succeeded   The object has been successfully reconciled   62s
redhat-operators-packages      Succeeded   The object has been successfully reconciled   62s
----